publish:
    docker:
        username: $$DOCKER_USER
        password: $$DOCKER_PASS
        email: $$DOCKER_EMAIL
        repo: pcallier/jupyter-stan
        tag: latest
        when:
            branch: master

build:
    image: ubuntu
    commands:
        - echo User
        - echo $$DOCKER_USER

