publish:
    docker:
        username: $$DOCKER_USER
        password: $$DOCKER_PASS
        email: $$DOCKER_EMAIL
        repo: plugins/drone-docker
        tag: latest
        when:
            branch: master

        
